<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d7fa22b2-7101-4892-a7f0-b3d93f2dce99</UserSecretsId>
    <DebuggerSupport>true</DebuggerSupport>
    <CopyOutputSymbolsToPublishDirectory>true</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Fluxor.Blazor.Web" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.7" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration)=='Debug'">
    <PackageReference Include="Fluxor.Blazor.Web.ReduxDevTools" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\TTV.Web.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\lib\" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Shared\AppFooter.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Pages\Policies\Cookies\Index.razor" />
    <_ContentIncludedByDefault Remove="Pages\Policies\Privacy\Index.razor" />
    <_ContentIncludedByDefault Remove="Pages\Policies\TermsAndConditions\Index.razor" />
    <_ContentIncludedByDefault Remove="Shared\AppFooter.razor" />
    <_ContentIncludedByDefault Remove="Shared\CookieConsent.razor" />
    <_ContentIncludedByDefault Remove="Shared\FullHeightLoading.razor" />
    <_ContentIncludedByDefault Remove="Shared\TestEnvironmentBanner.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Policies\TermsAndConditions\Index.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Policies\Privacy\Index.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Pages\Policies\Cookies\Index.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Shared\FullHeightLoading.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Shared\CookieConsent.razor" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Shared\TestEnvironmentBanner.razor" />
  </ItemGroup>

</Project>
