<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTV.Domain\TTV.Domain.csproj" />
    <ProjectReference Include="..\TTV.Web\Shared\TTV.Web.Shared.csproj" />
  </ItemGroup>

</Project>
