// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTV.Infrastructure.DataAccess;

#nullable disable

namespace TTV.DatabaseDeploy.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230821114519_TTV_Add_Orders_Vouchers")]
    partial class TTV_Add_Orders_Vouchers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LessonTag", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("LessonId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LessonTag");
                });

            modelBuilder.Entity("OrderLesson", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("LessonId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLesson");
                });

            modelBuilder.Entity("TTV.Domain.Entities.DiscountVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ClaimedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClaimedById");

                    b.ToTable("DiscountVoucher", (string)null);
                });

            modelBuilder.Entity("TTV.Domain.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonType")
                        .HasColumnType("int")
                        .HasColumnName("LessonTypeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonType");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("TTV.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PlacedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PlacedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("StatusId");

                    b.Property<string>("StatusReason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlacedById");

                    b.HasIndex("Status");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("TTV.Domain.Entities.OrderDiscountVoucher", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId", "VoucherId");

                    b.HasIndex("VoucherId");

                    b.ToTable("OrderDiscountVoucher", (string)null);
                });

            modelBuilder.Entity("TTV.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("TTV.Domain.Entities.TagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TagCategory", (string)null);
                });

            modelBuilder.Entity("TTV.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", "user");
                });

            modelBuilder.Entity("TTV.Domain.Entities.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.Property<int>("VideoType")
                        .HasColumnType("int")
                        .HasColumnName("VideoTypeId");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("VideoType");

                    b.ToTable("Video", (string)null);
                });

            modelBuilder.Entity("TTV.Infrastructure.DataAccess.Configuration.LookupEntity<TTV.Domain.Entities.LessonType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LessonType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Video"
                        });
                });

            modelBuilder.Entity("TTV.Infrastructure.DataAccess.Configuration.LookupEntity<TTV.Domain.Entities.OrderStatus>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "New"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("TTV.Infrastructure.DataAccess.Configuration.LookupEntity<TTV.Domain.Entities.VideoType>", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Full Lesson"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Intro"
                        });
                });

            modelBuilder.Entity("UserLesson", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LessonId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLesson");
                });

            modelBuilder.Entity("LessonTag", b =>
                {
                    b.HasOne("TTV.Domain.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTV.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderLesson", b =>
                {
                    b.HasOne("TTV.Domain.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTV.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TTV.Domain.Entities.DiscountVoucher", b =>
                {
                    b.HasOne("TTV.Domain.Entities.User", "ClaimedBy")
                        .WithMany()
                        .HasForeignKey("ClaimedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClaimedBy");
                });

            modelBuilder.Entity("TTV.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("TTV.Infrastructure.DataAccess.Configuration.LookupEntity<TTV.Domain.Entities.LessonType>", null)
                        .WithMany()
                        .HasForeignKey("LessonType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("TTV.Domain.Entities.Price", "Prices", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<DateTime>("EffectiveDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("LessonId")
                                .HasColumnType("int");

                            b1.Property<decimal?>("PromoAmount")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("LessonId");

                            b1.ToTable("Price", (string)null);

                            b1.WithOwner("Lesson")
                                .HasForeignKey("LessonId");

                            b1.Navigation("Lesson");
                        });

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("TTV.Domain.Entities.Order", b =>
                {
                    b.HasOne("TTV.Domain.Entities.User", "PlacedBy")
                        .WithMany("Orders")
                        .HasForeignKey("PlacedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTV.Infrastructure.DataAccess.Configuration.LookupEntity<TTV.Domain.Entities.OrderStatus>", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlacedBy");
                });

            modelBuilder.Entity("TTV.Domain.Entities.OrderDiscountVoucher", b =>
                {
                    b.HasOne("TTV.Domain.Entities.Order", "Order")
                        .WithMany("AppliedVouchers")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTV.Domain.Entities.DiscountVoucher", "Voucher")
                        .WithMany("OrdersAppliedTo")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("TTV.Domain.Entities.Tag", b =>
                {
                    b.HasOne("TTV.Domain.Entities.TagCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TTV.Domain.Entities.Video", b =>
                {
                    b.HasOne("TTV.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Videos")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTV.Infrastructure.DataAccess.Configuration.LookupEntity<TTV.Domain.Entities.VideoType>", null)
                        .WithMany()
                        .HasForeignKey("VideoType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("UserLesson", b =>
                {
                    b.HasOne("TTV.Domain.Entities.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTV.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TTV.Domain.Entities.DiscountVoucher", b =>
                {
                    b.Navigation("OrdersAppliedTo");
                });

            modelBuilder.Entity("TTV.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("TTV.Domain.Entities.Order", b =>
                {
                    b.Navigation("AppliedVouchers");
                });

            modelBuilder.Entity("TTV.Domain.Entities.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
