<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Notifications\Templates\OrderCancelledTemplate.mustache" />
    <None Remove="Notifications\Templates\OrderCompletedTemplate.mustache" />
    <None Remove="Notifications\Templates\OrderConfirmationTemplate.mustache" />
    <None Remove="Notifications\Templates\PasswordResetTemplate.mustache" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Notifications\Templates\OrderCancelledTemplate.mustache" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Notifications\Templates\OrderCompletedTemplate.mustache" />
    <EmbeddedResource Include="Notifications\Templates\OrderConfirmationTemplate.mustache" />
    <EmbeddedResource Include="Notifications\Templates\PasswordResetTemplate.mustache" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Stubble.Core" Version="1.10.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TTV.Application\TTV.Application.csproj" />
  </ItemGroup>

</Project>
