<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7b39ae7b-50a4-4f40-bf75-4fd8e343d7da</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Videos\TTV-Intro-Placeholder.mp4" />
    <None Remove="Videos\TTV-Lesson-Placeholder.mp4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Videos\TTV-Intro-Placeholder.mp4" />
    <Content Include="Videos\TTV-Lesson-Placeholder.mp4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.10" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.10" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\TTV.Application\TTV.Application.csproj" />
    <ProjectReference Include="..\..\TTV.Domain\TTV.Domain.csproj" />
    <ProjectReference Include="..\..\TTV.Infrastructure\TTV.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\TTV.Web.Shared.csproj" />
  </ItemGroup>

</Project>
